import { Box, Button, Chip, Typography } from '@mui/material';
import CorePageShell, { CoreMetricCards, Person, SectionCard } from '../../components/CorePageShell.jsx';

const members = [['PS', 'Priya Sharma', 'ABC Medical Imaging', '45', '6', 'PENDING', 'PRESENT'], ['AR', 'Aditya Rao', 'Ortho Kids', '52', '3', 'DONE', 'PRESENT'], ['SI', 'Sneha Iyer', 'Spine Indexing', '38', '9', 'DONE', 'PRESENT'], ['KP', 'Karan Patel', 'ABC Medical Imaging', '41', '4', 'DONE', 'LEAVE'], ['DM', 'Divya Menon', 'Cardio Records', '49', '2', 'PENDING', 'PRESENT']];
const bars = [['Mon', 120, 115], ['Tue', 145, 138], ['Wed', 98, 94], ['Thu', 167, 147], ['Fri', 152, 134], ['Sat', 88, 84]];

function CompletionSplit() {
  return <Box sx={{ height: 210, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 5, '@media (max-width: 500px)': { gap: 2, flexDirection: 'column', height: 270 } }}><Box sx={{ width: 150, height: 150, borderRadius: '50%', background: 'conic-gradient(#20a36b 0 63%, #e09a20 63% 85%, #3478ed 85% 100%)', display: 'grid', placeItems: 'center' }}><Box sx={{ width: 96, height: 96, borderRadius: '50%', bgcolor: '#fff', display: 'grid', placeItems: 'center', textAlign: 'center' }}><strong style={{ fontSize: 23 }}>78%</strong><small style={{ color: '#667085' }}>Completed</small></Box></Box><Box sx={{ display: 'grid', gap: 1, fontSize: 12 }}><span><b style={{ color: '#20a36b' }}>■</b> Completed · 980</span><span><b style={{ color: '#e09a20' }}>■</b> Pending · 270</span><span><b style={{ color: '#3478ed' }}>■</b> In review · 145</span></Box></Box>;
}

export default function Dashboard({ onNavigate }) {
  return <CorePageShell title="Team dashboard" description="Production and acknowledgement status for your team across assigned projects." headerExtra={<Button variant="outlined" sx={{ bgcolor: '#fff' }} onClick={() => onNavigate('reports')}>Export report</Button>} actionLabel="Review approvals" actionIcon={null} actionHandler={() => onNavigate('corrections')}>
    <CoreMetricCards items={[['Team size', '8'], ['Completed today', '362', '▲ 8% vs yday'], ['Pending approvals', '4', '2 correction reqs'], ['Ack. compliance', '86%', '2 pending']]}/>
    <Box sx={{ display: 'grid', gridTemplateColumns: '1.6fr 1fr', gap: 2, '@media (max-width: 800px)': { gridTemplateColumns: '1fr' } }}><SectionCard title="Team productivity — this week" action={<Button size="small">Details</Button>}><Box sx={{ height: 210, display: 'flex', alignItems: 'end', justifyContent: 'space-around', px: 2, pb: 2 }}>{bars.map(([day, value, barHeight], index) => <Box key={day} sx={{ width: 46, height: 180, position: 'relative', display: 'flex', alignItems: 'end', justifyContent: 'center', pb: 3, boxSizing: 'border-box' }}><Box sx={{ width: 46, height: barHeight, bgcolor: index === 5 ? '#8060d9' : '#3478ed', borderRadius: '7px 7px 0 0', position: 'relative' }}><Typography sx={{ position: 'absolute', top: -22, width: 46, textAlign: 'center', fontSize: 11, fontWeight: 700 }}>{value}</Typography></Box><Typography sx={{ position: 'absolute', bottom: 0, width: 46, textAlign: 'center', fontSize: 11, color: '#526581' }}>{day}</Typography></Box>)}</Box></SectionCard><SectionCard title="Completion split"><CompletionSplit /></SectionCard></Box>
    <SectionCard title="Team members" action={<Button size="small" onClick={() => onNavigate('my-team')}>Manage team</Button>}><Box sx={{ overflow: 'auto' }}><Box sx={{ display: 'grid', gridTemplateColumns: 'minmax(170px, 1.3fr) minmax(180px, 1.4fr) 90px 90px 125px 100px', minWidth: 855, px: 2, py: 1.1, bgcolor: '#f8fafc', color: '#526581', fontSize: 11, fontWeight: 700 }}><span>MEMBER</span><span>PROJECT</span><span>COMPLETED</span><span>PENDING</span><span>GUIDE ACK.</span><span>STATUS</span></Box>{members.map(([initials, name, project, completed, pending, guide, status]) => <Box key={name} sx={{ display: 'grid', gridTemplateColumns: 'minmax(170px, 1.3fr) minmax(180px, 1.4fr) 90px 90px 125px 100px', minWidth: 855, alignItems: 'center', px: 2, py: 1.1, borderTop: '1px solid #e3e8ef', fontSize: 12 }}><Person initials={initials} name={name} /><span>{project}</span><strong>{completed}</strong><span>{pending}</span><Chip label={guide} size="small" color={guide === 'DONE' ? 'success' : 'warning'} sx={{ width: 88, fontSize: 10, fontWeight: 800 }} /><Chip label={status} size="small" color={status === 'PRESENT' ? 'success' : 'default'} sx={{ width: 78, fontSize: 10, fontWeight: 800 }} /></Box>)}</Box></SectionCard>
  </CorePageShell>;
}
